@startuml domain
title Ergonaut - Domain

package "Ergonaut.Core" {

  class Project {
    +Id: Guid
    +Title: string
    +Description: string?
    +CreatedAt: DateTime
    +CreatedBy: Guid
  }
  Project "1" o-- "many" WorkItem
  Project "many" -- "1" User : created by

  class WorkItem {
    +Id: Guid
    +ProjectId: Guid
    +Title: string
    +Description: string?
    +CreatedAt: DateTime
    +Status: WorkItemStatus
    +DueDate: DateTime?
  }
  WorkItem "many" -- "1" User : created by
  WorkItem "many" -- "0..1" User : assigned to



  class User {
    +Id: Guid
    +Username: string
    +Role: UserRole
  }
}

package "Enums" {
enum WorkItemStatus {
  Todo
  InProgress
  Done
}

enum UserRole {
  Member
  Admin
}
}





@enduml
